[package]
name = "convert-to-binary"
version = "0.1.0"
authors = ["Arran France <arran@arranfrance.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
endio_bit = "0.2.0"
argh = "0.1.9"